CREATE TABLE [dbo].[user](
    [Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    [Name] VARCHAR(100) NULL,
    [Email] VARCHAR(255) NOT NULL UNIQUE,
    [Password] VARCHAR(255) NOT NULL,
    [CreatedAt] DATETIME2(0) NOT NULL DEFAULT GETDATE(),
    [LastLogin] DATETIME2(0) NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO